version: "3.8"

services:
  mysql:
    image: mysql:5.7.33
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: carpoolear
      MYSQL_USER: carpoolear
      MYSQL_PASSWORD: "@passAkjkas.78"
      MYSQL_ROOT_PASSWORD: holamundo
    volumes:
      - ./.db:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    image: movilizame-php82  
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    entrypoint: php artisan serve --host=0.0.0.0

